# Generated by Django 3.2.7 on 2021-10-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmingnewsapi',
            old_name='video',
            new_name='image',
        ),
    ]
