# Generated by Django 3.2.7 on 2021-10-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_rename_video_programmingnewsapi_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingnewsapi',
            name='image',
            field=models.ImageField(blank=True, upload_to='namefile'),
        ),
    ]
